name: item_news
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # icon图标
  cupertino_icons: ^1.0.2
  # 屏幕适配
  flutter_screenutil: ^5.9.0
  # 网络请求
  dio: ^5.3.2
  # 状态，路由，依赖管理
  get: ^4.6.6
  # 数据库【目前没用】
  sqflite: ^2.3.0
  # 持久化【目前没用】
#  shared_preferences: ^2.2.2
  # 路径
  path_provider: ^2.1.1
  # 刷新
  easy_refresh: ^3.3.2+1
  # 分享
  share_plus: ^7.2.1
  # 轮播【目前没用】
#  card_swiper: ^3.0.1
  # url跳转
  url_launcher: ^6.1.14
  # webview flutter实现
  flutter_inappwebview: ^5.8.0
  # 视差
#  flutter_tilt: ^2.0.10
  # 时间日期
  intl: ^0.18.1
  # ui 【可以移除，只用到加载组件】
  getwidget: ^2.0.4

# 开发环境
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # APP 图标
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "icon"
  ios: true
  image_path: "assets/daily.zhihu-1024x1024.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets\image\loading.gif
    - assets\daily.zhihu-1024x1024.png